routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('search', 'HomeController@search')->name( 'search');

Route::group(['prefix' => 'portals/{portal}'], function() {
	Route::resource( 'xpaths', 'ContentXpathController');
	Route::resource( 'sources', 'SourceController');
});

Route::resource( 'articles', 'ArticleController');
Route::resource( 'portals', 'PortalController');
Route::resource( 'topics', 'TopicController');
Route::resource( 'categories', 'CategoryController');
Route::resource( 'category_regex', 'RegexController');

resources/views/category_regex/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <form action="{{ route('category_regex.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="regex">Regex</label>
                        <input type="text" class="form-control" id="regex" aria-describedby="titleHelp" placeholder="Enter regex" value="" name="regex">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <input type="text" class="form-control" id="description" aria-describedby="descriptionHelp" placeholder="Enter description" value="" name="description">
                        <small id="descriptionHelp" class="form-text text-muted">Description.</small>
                    </div>
                    <div class="form-group">
                        <label>Categories</label><br>
                        @foreach ($categories as $category)
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="checkbox" id="category{{ $category->id }}" value="{{ $category->id }}" name="categories[]" {{ intval($_GET['category']) === $category->id?'checked':'' }}>
                                <label class="form-check-label" for="category{{ $category->id }}">{{ $category->name }}</label>
                            </div>
                        @endforeach
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/category_regex/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <form action="{{ route('category_regex.update', ['category_regex' => $regex]) }}" method="post">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label for="regex">Regex</label>
                        <input type="text" class="form-control" id="regex" aria-describedby="titleHelp" placeholder="Enter regex" value="{{ $regex->regex }}" name="regex" >
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <input type="text" class="form-control" id="description" aria-describedby="descriptionHelp" placeholder="Enter description" value="{{ $regex->description }}" name="description">
                        <small id="descriptionHelp" class="form-text text-muted">Description.</small>
                    </div>
                    <div class="form-group">
                        <label>Categories</label><br>
                        @foreach ($categories as $category)
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="checkbox" id="category{{ $category->id }}" value="{{ $category->id }}" name="categories[]" {{ $regex->categories->contains($category->id)?'checked':'' }}>
                                <label class="form-check-label" for="category{{ $category->id }}">{{ $category->name }}</label>
                            </div>
                        @endforeach
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/category_regex/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <table class="table table-striped">
                    <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>Regex</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($regexes as $regex)
                        <tr>
                            <td><a href="{{ route('category_regex.edit', ['id' => $regex->id]) }}">{{ $regex->id }}</a></td>
                            <td><a href="{{ route('category_regex.edit', ['id' => $regex->id]) }}">{{ $regex->name }}</a></td>
                            <td>{{ $regex->description }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection