routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('search', 'HomeController@search')->name( 'search');

Route::group(['prefix' => 'portals/{portal}'], function() {
	Route::resource( 'xpaths', 'ContentXpathController');
	Route::resource( 'sources', 'SourceController');
});

Route::resource( 'articles', 'ArticleController');
Route::resource( 'portals', 'PortalController');
Route::resource( 'topics', 'TopicController');
Route::resource( 'categories', 'CategoryController');
Route::resource( 'category_regex', 'RegexController');

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\DatabaseModels\Article;
use App\DatabaseModels\Topic;
use App\Repositories\ArticleRepository;
use Illuminate\Http\Request;

class TopicController extends Controller
{
	private $article;

	public function __construct(ArticleRepository $article) {
		$this->article = $article;
		$this->middleware('auth')->except( ['index', 'show']);
	}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::all();
        return view('topics.index', ['topics'=>$topics]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
	    return view('topics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    $validatedData = $request->validate([
		    'title' => 'required',
		    'overtitle' => 'required',
		    'query' => 'required',
		    'app' => 'boolean',
		    'active' => 'boolean',
		    'private' => 'boolean',
            'image' => 'file',
            'order' => 'integer'
	    ]);
	    if (!isset($validatedData['active'])) {
	    	$validatedData['active'] = true;
	    }
	    if (!isset($validatedData['private'])) {
		    $validatedData['private'] = true;
	    }
	    if (isset($validatedData['image'])) {
		    $file                   = $request->image->store( 'images', 'public' );
		    $validatedData['image'] = $file;
	    }
    	$topic = Topic::create($validatedData);
        return redirect()->route('topics.show', ['topic' => $topic]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
    	$articles = $this->article->search( $topic->query );
	    return view('topics.show', ['topic'=>$topic, 'articles' => $articles]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
	    return view('topics.edit', ['topic'=>$topic]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $topic)
    {
	    $validatedData = $request->validate([
		    'title' => 'required',
		    'overtitle' => 'required',
		    'query' => 'required',
		    'app' => 'boolean',
		    'active' => 'boolean',
		    'private' => 'boolean',
            'image' => 'file',
            'order' => 'integer'
	    ]);
	    if (isset($validatedData['image'])) {
		    $file                   = $request->image->store( 'images', 'public' );
		    $validatedData['image'] = $file;
	    }
	    $topic->update($validatedData);
	    return view('topics.edit', ['topic'=>$topic]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
    	$topic->delete();
        return redirect()->route('topics.index');
    }
}

resources/views/topics/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <form action="{{ route('topics.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title" value="" name="title">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="overtitle">Overtitle</label>
                        <input type="text" class="form-control" id="overtitle" aria-describedby="overtitleHelp" placeholder="Enter overtitle" value="" name="overtitle">
                        <small id="overtitleHelp" class="form-text text-muted">Overtitle used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="overtitle">Query</label>
                        <input type="text" class="form-control" id="query" aria-describedby="queryHelp" placeholder="Enter query" value="" name="query">
                        <small id="queryHelp" class="form-text text-muted">Query used for selecting items.</small>
                    </div>
                    <div class="form-group">
                        <label for="order">Order</label>
                        <input type="number" step="1" min="0" class="form-control" id="order"
                               aria-describedby="orderHelp" placeholder="Order" value="" name="order">
                        <small id="orderHelp" class="form-text text-muted">Ordering in app</small>
                    </div>
                    <div class="form-group">
                        <input class="form-check-input" type="checkbox" value="1" name="app" id="in_app">
                        <label class="form-check-label" for="in_app">
                            In App
                        </label>
                    </div>
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" name="image" accept="image/*">
                            <label class="custom-file-label" for="image">Topic image</label>
                        </div>
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/topics/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <form action="{{ route('topics.update', ['topic' => $topic]) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title" value="{{ $topic->title }}" name="title">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="overtitle">Overtitle</label>
                        <input type="text" class="form-control" id="overtitle" aria-describedby="overtitleHelp" placeholder="Enter overtitle" value="{{ $topic->overtitle }}" name="overtitle">
                        <small id="overtitleHelp" class="form-text text-muted">Overtitle used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="overtitle">Query</label>
                        <input type="text" class="form-control" id="query" aria-describedby="queryHelp" placeholder="Enter query" value="{{ $topic->query }}" name="query">
                        <small id="queryHelp" class="form-text text-muted">Query used for selecting items.</small>
                    </div>
                    <div class="form-group">
                        <label for="order">Order</label>
                        <input type="number" step="1" min="0" class="form-control" id="order"
                               aria-describedby="orderHelp" placeholder="Order" value="{{ $topic->order }}"
                               name="order">
                        <small id="orderHelp" class="form-text text-muted">Ordering in app</small>
                    </div>
                    <div class="form-group">
                        <input class="form-check-input" type="checkbox" value="1" name="app" id="in_app" {{ $topic->app?'checked':'' }}>
                        <label class="form-check-label" for="in_app">
                            In App
                        </label>
                    </div>
                    <div class="form-group">
                        @if($topic->image)
                            <img src="{{ $topic->image }}" class="col-md-12">
                        @endif
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" name="image" accept="image/*">
                            <label class="custom-file-label" for="image">Topic image</label>
                        </div>
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/topics/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                @auth
                <a href="{{ route('topics.create') }}" class="btn btn-primary btn-lg">New topic</a>
                @endauth
                <table class="table table-striped">
                    <thead class="thead-light">
                    <tr>
                        @auth
                        <th>#</th>
                        @endauth
                        <th>Topic</th>
                        <th>Order</th>
                        <th>In App</th>
                        @auth
                            <th>Actions</th>
                        @endauth
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($topics as $topic)
                        <tr>
                            @auth
                            <td><a href="{{ route('topics.edit', ['id' => $topic->id]) }}">{{ $topic->id }}</a></td>
                            @endauth
                            <td><a href="{{ route('topics.show', ['id' => $topic->id]) }}">{{ $topic->title }}</a></td>
                            <td>{{ $topic->order }}</td>
                            <td>{{ $topic->app?'Yes':'No' }}</td>
                            @auth
                                <td><a class="btn btn-primary btn-sm" href="{{ route('topics.edit', ['id' => $topic->id]) }}">Edit</a></td>
                            @endauth
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/topics/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif

                    @auth
                        <h2><a href="{{ route('topics.edit', ['topic' => $topic]) }}">{{ $topic->title }}</a></h2>
                    @elseauth
                        <h2>{{ $topic->title }}</h2>
                    @endauth

                @foreach($articles as $article)
                    <div class="card">
                        <div class="card-header"><a href="{{ $article->link }}" target="_blank">{{ $article->title }}</a>
                            <span class="float-right">{{ $article->virality_normalized }} / {{  $article->virality_absolute }}</span>
                            @auth
                                <a class="btn btn-primary btn-sm float-right" href="{{ route('articles.show', ['article' => $article]) }}">Details</a>
                            @endauth
                        </div>
                        <a href="{{ $article->link }}" target="_blank"><img class="card-img-top" src="{{ $article->image }}"></a>
                        <div class="card-body">
                            <p class="card-text">{{ $article->description }}</p>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>
@endsection