routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('search', 'HomeController@search')->name( 'search');

Route::group(['prefix' => 'portals/{portal}'], function() {
	Route::resource( 'xpaths', 'ContentXpathController');
	Route::resource( 'sources', 'SourceController');
});

Route::resource( 'articles', 'ArticleController');
Route::resource( 'portals', 'PortalController');
Route::resource( 'topics', 'TopicController');
Route::resource( 'categories', 'CategoryController');
Route::resource( 'category_regex', 'RegexController');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\DatabaseModels\Article;
use App\DatabaseModels\Category;
use App\Repositories\ArticleRepository;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
	private $article;

	public function __construct(ArticleRepository $article) {
		$this->article = $article;
		$this->middleware('auth')->except( ['index', 'show']);
	}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories.index', ['categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
	    return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    $validatedData = $request->validate([
		    'name' => 'required',
		    'image' => 'file',
            'keywords' => 'present',
            'order' => 'integer'
	    ]);
	    if (isset($validatedData['image'])) {
		    $file                   = $request->image->store( 'images', 'public' );
		    $validatedData['image'] = $file;
	    }
	    else {
	    	$validatedData['image'] = ' ';
	    }
	    $inclusive = [];
	    foreach (explode(',', $validatedData['keywords']) as $word) {
	    	$inclusive[] = trim($word);
	    }
	    $validatedData['keywords'] = ['inclusive' => $inclusive];
    	$category = Category::create($validatedData);
        return redirect()->route('categories.show', ['category' => $category]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
    	$category->load(['articles' => function($query) {
    		$query->limit(10)->orderBy('id', 'desc');
	    }]);
	    return view('categories.show', ['category'=>$category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
	    return view('categories.edit', ['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
	    $validatedData = $request->validate([
		    'name' => 'required',
		    'image' => 'file',
            'keywords' => 'present',
            'order' => 'integer'
	    ]);
	    if (isset($validatedData['image'])) {
		    $file                   = $request->image->store( 'images', 'public' );
		    $validatedData['image'] = $file;
	    }
	    $inclusive = [];
	    foreach (explode(',', $validatedData['keywords']) as $word) {
		    $inclusive[] = trim($word);
	    }
	    $validatedData['keywords'] = ['inclusive' => $inclusive];
	    $category->update($validatedData);
	    return redirect()->route('categories.edit', ['category'=>$category]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
    	$category->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title" value="" name="name">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="order">Order</label>
                        <input type="number" step="1" min="0" class="form-control" id="order"
                               aria-describedby="orderHelp" placeholder="Order" value="" name="order">
                        <small id="orderHelp" class="form-text text-muted">Ordering in app</small>
                    </div>
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" name="image" accept="image/*">
                            <label class="custom-file-label" for="image">Category image</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="keywords">Keywords</label>
                        <input type="text" class="form-control" id="keywords" aria-describedby="wordsHelp" placeholder="Enter keywords" value="" name="keywords">
                        <small id="wordsHelp" class="form-text text-muted">Comma separated keywords to match in URL.</small>
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <form action="{{ route('categories.update', ['category' => $category]) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title" value="{{ $category->name }}" name="name">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="order">Order</label>
                        <input type="number" step="1" min="0" class="form-control" id="order"
                               aria-describedby="orderHelp" placeholder="Order" value="{{ $category->order }}"
                               name="order">
                        <small id="orderHelp" class="form-text text-muted">Ordering in app</small>
                    </div>
                    <div class="form-group">
                        @if($category->image)
                            <img src="{{ $category->image }}" class="col-md-12">
                        @endif
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" name="image" accept="image/*">
                            <label class="custom-file-label" for="image">Category image</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="keywords">Keywords</label>
                        <input type="text" class="form-control" id="keywords" aria-describedby="wordsHelp" placeholder="Enter keywords" value="{{ isset($category->keywords['inclusive'])?implode(', ', $category->keywords['inclusive']):'' }}" name="keywords">
                        <small id="wordsHelp" class="form-text text-muted">Comma separated keywords to match in URL.</small>
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
        <br><br>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <a class="btn btn-primary" href="{{ route('category_regex.create', ['category' => $category]) }}">Add regex</a><br><br>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Regex</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($category->regexes as $regex)
                        <tr>
                            <td><a href="{{ route('category_regex.edit', ['category_regex' => 'regex']) }}">{{ $regex->id }}</a></td>
                            <td><a href="{{ route('category_regex.edit', ['category_regex' => 'regex']) }}">{{ $regex->regex }}</a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                @auth
                <a href="{{ route('categories.create') }}" class="btn btn-primary btn-lg">New category</a><br><br>
                @endauth
                <table class="table table-striped">
                    <thead class="thead-light">
                    <tr>
                        @auth
                        <th>#</th>
                        @endauth
                        <th>Category</th>
                        <th>Order</th>
                        @auth
                        <th>Actions</th>
                        @endauth
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            @auth
                            <td><a href="{{ route('categories.edit', ['id' => $category->id]) }}">{{ $category->id }}</a></td>
                            @endauth
                            <td><a href="{{ route('categories.show', ['id' => $category->id]) }}">{{ $category->name }}</a></td>
                            <td>{{ $category->order }}</td>
                            @auth
                                    <td><a class="btn btn-primary btn-sm" href="{{ route('categories.edit', ['id' => $category->id]) }}">Edit</a></td>
                            @endauth
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif

                    @auth
                        <h2><a href="{{ route('categories.edit', ['category' => $category]) }}">{{ $category->title }}</a></h2>
                    @elseauth
                        <h2>{{ $category->title }}</h2>
                    @endauth

                @foreach($category->articles as $article)
                    <div class="card">
                        <div class="card-header"><a href="{{ $article->link }}" target="_blank">{{ $article->title }}</a>
                            <span class="float-right">{{ $article->virality_normalized }} / {{  $article->virality_absolute }}</span>
                            @auth
                                <a class="btn btn-primary btn-sm float-right" href="{{ route('articles.show', ['article' => $article]) }}">Details</a>
                            @endauth
                        </div>
                        <a href="{{ $article->link }}" target="_blank"><img class="card-img-top" src="{{ $article->image }}"></a>
                        <div class="card-body">
                            <p class="card-text">{{ $article->description }}</p>
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>
@endsection