routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('search', 'HomeController@search')->name( 'search');

Route::group(['prefix' => 'portals/{portal}'], function() {
	Route::resource( 'xpaths', 'ContentXpathController');
	Route::resource( 'sources', 'SourceController');
});

Route::resource( 'articles', 'ArticleController');
Route::resource( 'portals', 'PortalController');
Route::resource( 'topics', 'TopicController');
Route::resource( 'categories', 'CategoryController');
Route::resource( 'category_regex', 'RegexController');

app/Http/Controllers/PortalController.php
<?php

namespace App\Http\Controllers;

use App\DatabaseModels\Article;
use App\DatabaseModels\Category;
use App\DatabaseModels\Portal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PortalController extends Controller
{
	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth')->except( ['index', 'show']);
	}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $portals = Portal::all();
        return view('portals.index', ['portals' => $portals]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('portals.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    $validatedData = $request->validate([
		    'name' => 'required',
		    'url' => 'required'
	    ]);
	    $portal = Portal::create($validatedData);
	    if ($request->has( 'categories')) {
		    $portal->categories()->attach( $request->input('categories'));
	    }
	    return redirect()->route('portals.edit', ['portal' => $portal])->with( 'status', 'Portal created');
    }

    /**
     * Display the specified resource.
     *
     * @param  Portal  $portal
     * @return \Illuminate\Http\Response
     */
    public function show(Portal $portal)
    {
        $portal->load(['articles' => function($query) {
        	$query->limit(10)->orderBy('id', 'desc');
        }]);

        return view('portals.show', ['portal' => $portal]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Portal  $portal
     * @return \Illuminate\Http\Response
     */
    public function edit(Portal $portal)
    {
    	$categories = Category::all();
        return view('portals.edit', ['portal' => $portal, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Portal  $portal
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Portal $portal)
    {
	    $validatedData = $request->validate([
		    'name' => 'required',
		    'url' => 'required'
	    ]);
	    $portal->update($validatedData);
	    if ($request->has( 'categories')) {
		    $portal->categories()->sync( $request->input('categories'));
	    }
	    else {
		    $portal->categories()->detach();
	    }
	    return redirect()->route('portals.edit', ['portal' => $portal])->with( 'status', 'Portal updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Portal  $portal
     * @return \Illuminate\Http\Response
     */
    public function destroy(Portal $portal)
    {
        //
    }
}

resources/views/portals/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                    <form action="{{ route('portals.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title" value="{{ old('name') }}" name="name">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="homepage">Homepage</label>
                        <input type="text" class="form-control" id="homepage" aria-describedby="urlHelp" placeholder="Enter homepage" value="{{ old('url') }}" name="url">
                        <small id="urlHelp" class="form-text text-muted">Link to homepage.</small>
                    </div>
                        <div class="form-group">
                            <label>Categories</label><br>
                            @foreach ($categories as $category)
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" id="category{{ $category->id }}" value="{{ $category->id }}" name="categories[]">
                                    <label class="form-check-label" for="category{{ $category->id }}">{{ $category->name }}</label>
                                </div>
                            @endforeach
                        </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/portals/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                    <form action="{{ route('portals.update', ['portal' => $portal]) }}" method="post">
                    @csrf
                        @method('put')
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" aria-describedby="titleHelp" placeholder="Enter title" value="{{ $portal->name }}" name="name">
                        <small id="titleHelp" class="form-text text-muted">Title used for display.</small>
                    </div>
                    <div class="form-group">
                        <label for="homepage">Homepage</label>
                        <input type="text" class="form-control" id="homepage" aria-describedby="urlHelp" placeholder="Enter homepage" value="{{ $portal->url }}" name="url">
                        <small id="urlHelp" class="form-text text-muted">Link to homepage.</small>
                    </div>
                        <div class="form-group">
                            <label>Categories</label><br>
                            @foreach ($categories as $category)
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" id="category{{ $category->id }}" value="{{ $category->id }}" name="categories[]" {{ $portal->categories->contains($category->id)?'checked':'' }}>
                                    <label class="form-check-label" for="category{{ $category->id }}">{{ $category->name }}</label>
                                </div>
                            @endforeach
                        </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                    <br><br>
                    <h2>Sources</h2>
                    <a class="btn btn-primary" href="{{ route('sources.create', ['portal'=>$portal]) }}">Add Source</a><br><br>
                    <table class="table table-striped">
                    <thead class="thead-light">
                        <tr>
                            <th>Source</th>
                            <th>Type</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($portal->sources as $source)
                        <tr>
                            <td>{{ $source->url }}</td>
                            <td>{{ $source->type }}</td>
                            <td><a class="btn btn-sm btn-primary" href="{{ route('sources.edit', ['portal' => $portal, 'source' => $source]) }}">Edit</a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                    <br><br>
                    <h2>Content Xpaths</h2>
                    <a class="btn btn-primary" href="{{ route('xpaths.create', ['portal'=>$portal]) }}">Add Xpath</a><br><br>
                    <table class="table table-striped">
                        <thead class="thead-light">
                        <tr>
                            <th>Xpath</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($portal->xpaths as $xpath)
                            <tr>
                                <td>{{ $xpath->xpath }}</td>
                                <td><a class="btn btn-sm btn-primary" href="{{ route('xpaths.edit', ['portal' => $portal, 'xpath' => $xpath]) }}">Edit</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
@endsection

resources/views/portals/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                @auth
                    <a class="btn btn-primary btn-lg" href="{{ route('portals.create') }}">Add portal</a><br><br>
                @endauth
                <table class="table table-striped">
                    <thead class="thead-light">
                        <tr>
                            @auth
                            <th>#</th>
                            @endauth
                            <th>Portal</th>
                            <th>Homepage</th>
                                <th>Sources</th>
                                <th>Frequency</th>
                                <th>Virality</th>
                                <th>Articles</th>
                                <th>Last</th>
                            @auth
                            <th>Actions</th>
                            @endauth
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($portals as $portal)
                        <tr>
                            @auth
                            <td><a href="{{ route('portals.edit', ['id' => $portal->id]) }}">{{ $portal->id }}</a></td>
                            @endauth
                            <td><a href="{{ route('portals.show', ['id' => $portal->id]) }}">{{ $portal->name }}</a></td>
                            <td><a href="{{ $portal->url }}" target="_blank">{{ $portal->url }}</a></td>
                                <td>{{ $portal->sources_count }}</td>
                                <td>{{ $portal->frequency }}</td>
                                <td>{{ $portal->virality }}</td>
                                <td>{{ $portal->articles_count }}</td>
                                <td>{{ $portal->last_article }}</td>
                            @auth
                            <td><a class="btn btn-primary btn-sm" href="{{ route('portals.edit', ['id' => $portal->id]) }}">Edit</a></td>
                            @endauth
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/portals/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
                <h2>{{ $portal->title }}</h2>
                @foreach($portal->articles as $article)
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ $article->link }}" target="_blank">{{ $article->title }}</a>
                            <span class="float-right">{{ $article->virality_normalized }} / {{  $article->virality_absolute }}</span>
                            <a class="btn btn-primary btn-sm float-right" href="{{ route('articles.show', ['article' => $article]) }}">Details</a>
                        </div>
                        <a href="{{ $article->link }}" target="_blank"><img class="card-img-top" src="{{ $article->og_image }}"></a>
                        <div class="card-body">
                            <p class="card-text">{{ $article->description }}</p>
                        </div>
                    </div>
                @endforeach

        </div>
    </div>
</div>
@endsection